### ISSUE TITLE
非root 方法

### ISSUE THREAD

**Issue by 10032** [lack006/OnePlus12-OxygenOS-wallet-mainland-China-localization#1]
有没有非root的方案？

**Comment by lack006** [comment]
模块的原理是 
删除 氧OS的 /system/product/priv-app/KeKeUserCenter 账号程序，并安装 /system/product/priv-app
/KeKeUserCenterAccount 的帐号中心，需要对product分区进行读写操作，一般情况下是需要root权限，不过有其他奇技淫巧，你可以在氧OS中单独手动刷入 Color os的 product分区，这样就不需要模块也不需要root就可以使用大陆的钱包和账号了，不过会造成OTA和其他问题。

**Comment by 10032** [comment]
> 是

感谢，但是😅我锁bl了，有没有可能用lspatch的方法实现？

**Comment by lack006** [comment]
> 感谢，但是😅我锁bl了，有没有可能用lspatch的方法实现？

这个应该需要去逆向 设置 程序或者 氧OS 的账号中心程序，我不是很了解哈，不能提供帮助
